Crocodile booting
hexagon-geo-surv/u-boot pull request #101
Opened 2022-04-21 13:13 UTC by htho-lgs

Support platform 1600 booting (bootscript)

2022-04-22 07:05 UTC, zandrey requested changes

2022-04-22 08:49 UTC, htho-lgs commented
V2:
- deactivate usdhc1 node
- add copyright statement to `bootmap.c`

2022-04-26 14:27 UTC, htho-lgs commented
V3:
- set `swu=1` in default environment

2022-04-26 19:09 UTC, zandrey approved these changes

2022-04-26 19:09 UTC, zandrey commented on include/configs/crocodile.h
> +	"swu=1\0" \
Minor: padding

2022-04-27 08:01 UTC, merged